# Generated by Django 3.2.25 on 2024-06-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_on_sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProductsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(blank=True, max_length=2, null=True)),
                ('saved_products_item_price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_product', to='saved_products.savedproductslist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
