# Generated by Django 3.2.25 on 2024-06-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproductslist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedproductslist',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
