# Generated by Django 3.2.25 on 2024-06-04 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_products', '0002_auto_20240604_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproductslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
