# Generated by Django 3.2.25 on 2024-03-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Sub')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
