# Generated by Django 3.2.25 on 2024-03-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240329_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Sub')], editable=False),
        ),
    ]
