# Generated by Django 3.2.25 on 2024-04-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=18, limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category'),
        ),
    ]
