# Generated by Django 3.2.25 on 2024-06-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Parent'), (1, 'Child')], editable=False),
        ),
    ]
