# Generated by Django 3.2.25 on 2024-07-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantity_available',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_requested',
            field=models.IntegerField(default=0),
        ),
    ]
