# Generated by Django 3.2.25 on 2024-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20240730_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='deal',
            field=models.IntegerField(choices=[(0, 0), (1, 5), (2, 10), (3, 20), (4, 25)], default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL')], default=0),
        ),
    ]
